apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-demo-order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: us-central1-docker.pkg.dev/gke-demo-451811/gke-demo-order/order-service-image:latest
          ports:
            - containerPort: 8080
