apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: order-service
#   annotations:
#     cloud.google.com/load-balancer-type: "External"
# spec:
#   # type: ClusterIP # for Internal 
#   type: LoadBalancer
#   selector:
#     app: order-service
#   ports:
#     - protocol: TCP
#       port: 80      # External port
#       targetPort: 8080  # Internal container port

